name: Spellcheck
on:
  pull_request:
    types: [synchronize, edited, opened]
  push:
    branches: [main]
jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Spellcheck
        uses: crate-ci/typos@master
